### ISSUE TITLE
Missing Parentheses in Error Formula with Product Rule

### ISSUE THREAD

**Issue by Firionus** [captain-joni/errorformulagenerator#1]
The error formula is missing a pair of parentheses when a derivative requires the product rule and contains a sum:

<img src="https://github.com/user-attachments/assets/6e79a063-06eb-465d-b1ca-4370862c64e0" width="50%">

Note that `Deltax` should be multiplied with `2*x` as well, and not just with `1`.

I think the parentheses need to be inserted here:

https://github.com/captain-joni/errorformulagenerator/blob/6225a360d2638f9c53b694e52a900af788407fb5/differ.py#L50

Maybe it works like this?

```py
        equation = "((" +  str(speicher_2["d_0"]) + ")*" + speicher_delta["delta_0"] + ")**2"
```

We're really enjoying not writing out all derivatives by hand, thanks for putting up the site🚀 🤩

**Comment by captain-joni** [comment]
Heyho Johannes,
you are absolutely right, thanks for poiting that out and providing the quick fix. 
I changed it now. And tried it with a few equations, it seems to work. 
Enjoy.
